🎨  Update Table to use forwardRef
equinor/design-system pull request #1014
Opened 2021-01-12 12:26 UTC by pomfrida

Resolves #810

2021-01-13 13:39 UTC, mimarz commented on libraries/core-react/src/components/Table/Head.tsx
> +type HeadProps = { children: ReactNode }
Should this not be `React.HTMLAttributes<HTMLTableHeaderCellElement>` type?

2021-01-13 13:40 UTC, mimarz commented on libraries/core-react/src/components/Table/Head.tsx
> +export const Head = ({ children, ...props }: HeadProps): JSX.Element => {
Missing use of `forwardRef` here

2021-01-13 13:41 UTC, mimarz requested changes
Seems to be some missing changes in `Cell` and `Body` for `forwardRef`?

2021-01-13 17:00 UTC, pomfrida commented
@mimarz I had some problems with the `ref` and the `TableHeaderCellElement` type in `Head`. It suggested to use `HTMLTableSectionElement` instead. Last commit with `Body` and `Head` fix 👍

2021-01-14 10:43 UTC, mimarz approved these changes
LGTM 👍

2021-01-14 13:02 UTC, merged