Adjustments for placements inside button
equinor/design-system pull request #1085
Opened 2021-01-26 12:37 UTC by mimarz

resolves #992 

Tried solutions:
* Different CSS Grid variants
* Flex

![image](https://user-images.githubusercontent.com/1070981/105845425-fc940380-5fda-11eb-96b0-a20b7a246c43.png)

2021-01-26 15:34 UTC, wenche approved these changes
So much work for so little code 😓

2021-01-27 07:52 UTC, vnys commented
How about something like this? https://codepen.io/vnys/pen/jOMgXNP

2021-01-27 14:36 UTC, mimarz commented
> How about something like this? https://codepen.io/vnys/pen/jOMgXNP Unless there’s something I haven’t thought of… But here you don’t need to know what the user sends in, just that the combinations are either icon + label, icon +. label + icon or label + icon.

Changed to use the css-grid approach you suggested. Had to add a `:only-child` and manipulate the `grid-template-columns` to only be one to work for `ghost_icon` variants of `Button`

2021-01-27 14:40 UTC, pomfrida approved these changes
LGTM 👍

2021-01-28 07:46 UTC, vnys requested changes
I think we should avoid `left` and `right` since that doesn’t take languages like Arabic into account. Suggest replacing them with `start` and `end`.

2021-01-28 08:59 UTC, vnys commented
As just mentioned on Slack, I didn’t think of the Ghost Icon button – then flex works better after all. Another day, another codepen → https://codepen.io/vnys/pen/ZEBzvrK

2021-01-28 09:01 UTC, mimarz commented
> As just mentioned on Slack, I didn’t think of the Ghost Icon button – then flex works better after all. Another day, another codepen → https://codepen.io/vnys/pen/ZEBzvrK

Ok, will test it out 👍

2021-01-28 09:32 UTC, vnys approved these changes
Smashing pumkins 👊🏻 🎃

2021-01-28 09:39 UTC, merged