Accordion - return <> if props hidden is true
equinor/design-system pull request #1103
Opened 2021-02-04 09:05 UTC by tfrausin

resolves #1102

2021-02-04 10:57 UTC, mimarz commented on libraries/core-react/src/components/Accordion/AccordionPanel.tsx
> +      return null;
Eslint check failed on `;` as we don't use semi-colons 🤓 Please remove

2021-02-04 10:59 UTC, mimarz requested changes
Super duper! 😄 

Just a small linting error that needs to be fixed before we can approve.

2021-02-05 09:38 UTC, mimarz requested changes
![tenor (2)](https://user-images.githubusercontent.com/1070981/107011594-24802580-6798-11eb-8b56-228743588101.gif)


Soo... having slept on this, I realise this would break the `Accordion` component in some use-cases 😴🕵️

Having the content not being rendered/mounted when closed would break SEO and server-side React rendering for this component. We still need the default behaviour to be that content is mounted as is behaviour today. 

We do realise however that there is a need for content not being rendered when closed, so we suggest introducing a optional `unmountOnCollapse` boolean property on `<Accordion>`, that lets users opt-in on content not being mounted when closed. If you could also write some testes to verify that its working as intended that would be great :) 

TDLR;
- [ ] We need a `unmountOnCollapse` boolean property on `<Accordion>`, if `true` and hidden=`true`, `AccordionPanel` return `null`. 
- [ ] Write tests to verify that everything works when the prop is either set or not.

2021-02-11 13:53 UTC, cbuv commented
I was hoping AccordionHeader's toggleExpanded callback could be used to solve this issue and similar ones by storing the expanded state  outside the eds accordian components. 

But, I tested the toggleExpanded, and it does not do anything. 
What is the status of toggleExpanded? @vnys

2021-02-18 08:20 UTC, mimarz commented
@tfrausin We would love to have this feature in our next release, any idea when you can do these changes? Do you need any assistance? :)

2021-02-18 09:15 UTC, tfrausin commented
@mimarz After discussing this within the team, we have unfortunately decided that we do not have the capacity to prioritize this to the extent necessary to fulfill your requirements. Hence, we're withdrawing our pull request.

2021-02-18 09:15 UTC, closed without merging