Update actions
equinor/design-system pull request #1146
Opened 2021-03-04 14:59 UTC by mimarz

2021-03-09 10:50 UTC, wenche requested changes
As mentioned in the standup today, I suggest we update `RELEASE.md` file according to this new regime as well 👍

2021-03-09 10:50 UTC, wenche commented on .eslintrc.js
> +      version: '^17.0.1',
Wish the original approach worked 🙈

2021-03-09 10:53 UTC, mimarz commented on .eslintrc.js
> +      version: '^17.0.1',
sparse-checkout... 🙈

2021-03-12 12:19 UTC, wenche requested changes
Looking good as far as I can see, but I guess we need to try it for ourselves to see how it works. 

Good job on automation 👍

2021-03-12 12:19 UTC, wenche commented on RELEASE.md
> +3. Add a release in github
Elaborate a bit here?

2021-03-12 12:22 UTC, wenche commented on RELEASE.md
> +3. Add a release in github
On the `3. Add a release in github`

2021-03-12 12:28 UTC, mimarz commented on RELEASE.md
> +3. Add a release in github
Done!

2021-03-12 12:31 UTC, wenche approved these changes
🥳

2021-03-12 12:32 UTC, merged