[WIP]: 📝  Release eds-core-react and eds-tokens
equinor/design-system pull request #1159
Opened 2021-03-16 09:03 UTC by wenche

Resolve #1140

2021-03-16 12:17 UTC, wenche commented
Suggestions for improvements @mimarz ?

2021-03-16 13:58 UTC, wenche commented
I'm not 100% sure about which date to add.

2021-03-17 11:12 UTC, pomfrida approved these changes
LGTM 👍

2021-03-17 11:13 UTC, pomfrida requested changes
Forgot to add dates

2021-03-17 11:13 UTC, pomfrida commented on libraries/core-react/CHANGELOG.md
> +## [0.9.0] - 2021-03-x
```suggestion
## [0.9.0] - 2021-03-17
```

2021-03-17 11:13 UTC, pomfrida commented on libraries/tokens/CHANGELOG.md
> +## [0.5.6] - 2021-02-x
```suggestion
## [0.5.6] - 2021-03-17
```

2021-03-17 11:18 UTC, pomfrida approved these changes
Now it's good to go 👍

2021-03-17 11:25 UTC, merged