removed all react import in components
equinor/design-system pull request #1251
Opened 2021-04-20 08:42 UTC by Serjeel-Ranjan-911

I have removed react import from all files possible.
```
'react/react-in-jsx-scope': 'off',
```
I didn't add the above line but it's still passing all the tests. 
Please let me know if I have missed something.

2021-04-20 08:47 UTC, pomfrida requested changes
Hi and thanks for your contribution! 👍  Please note your changes are not on our actual components (just Storefront components). All the EDS components are located in `design-system/libraries/core-react/src`

2021-04-20 08:51 UTC, Serjeel-Ranjan-911 commented
> Hi and thanks for your contribution! 👍 Please note your changes are not on our actual components (just Storefront components). All the EDS components are located in `design-system/libraries/core-react/src`

ohh ok. I thought I don't have to touch libraries. I will fix in next commit.

2021-04-20 08:54 UTC, Serjeel-Ranjan-911 commented
@pomfrida also what should I do with this import?
```
import * as React from 'react'
```

2021-04-20 08:55 UTC, mimarz commented
> I have removed react import from all files possible.
> 
> ```
> 'react/react-in-jsx-scope': 'off',
> ```
> 
> I didn't add the above line but it's still passing all the tests.
> Please let me know if I have missed something. fixes #1222

The linting might fail, but we'll see! 

Thanks for taking the time to help us clean up! 😊

2021-04-20 09:10 UTC, Serjeel-Ranjan-911 commented
> @pomfrida also what should I do with this import?
> 
> ```
> import * as React from 'react'
> ```

should I let it be there?

2021-04-20 09:10 UTC, pomfrida commented
> @pomfrida also what should I do with this import?
> 
> ```
> import * as React from 'react'
> ```

Please remove this too 👍

2021-04-20 09:19 UTC, Serjeel-Ranjan-911 commented
> > @pomfrida also what should I do with this import?
> > ```
> > import * as React from 'react'
> > ```
> 
> Please remove this too 👍

The typescript files are not allowing it's removal.  maybe refer [here](https://stackoverflow.com/questions/55285737/import-as-react-from-react-vs-import-react-from-react). 
![image](https://user-images.githubusercontent.com/74287984/115371404-92f55100-a1e7-11eb-8ffa-99643bfae368.png)
there are some functions using that import.

2021-04-20 09:22 UTC, mimarz commented
> > > @pomfrida also what should I do with this import?
> > > ```
> > > import * as React from 'react'
> > > ```
> > 
> > 
> > Please remove this too 👍
> 
> The typescript files are not allowing it's removal. maybe refer [here](https://stackoverflow.com/questions/55285737/import-as-react-from-react-vs-import-react-from-react).
> ![image](https://user-images.githubusercontent.com/74287984/115371404-92f55100-a1e7-11eb-8ffa-99643bfae368.png)
> there are some functions using that import.


What if you import them like the util functions?  

I think this should work:
```typescript
import type { KeyboardEvent } from 'react'
```

2021-04-20 09:26 UTC, Serjeel-Ranjan-911 commented
> > > > @pomfrida also what should I do with this import?
> > > > ```
> > > > import * as React from 'react'
> > > > ```
> > > 
> > > 
> > > Please remove this too 👍
> > 
> > 
> > The typescript files are not allowing it's removal. maybe refer [here](https://stackoverflow.com/questions/55285737/import-as-react-from-react-vs-import-react-from-react).
> > ![image](https://user-images.githubusercontent.com/74287984/115371404-92f55100-a1e7-11eb-8ffa-99643bfae368.png)
> > there are some functions using that import.
> 
> What if you import them like the util functions?
> 
> I think this should work:
> 
> ```ts
> import type { KeyboardEvent } from 'react'
> ```

Even components are having problems
```
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```
I receive this error for components. 

![image](https://user-images.githubusercontent.com/74287984/115372532-a228ce80-a1e8-11eb-8ddb-2c95f4f6fae9.png)

2021-04-20 10:42 UTC, mimarz commented
Ah, this is a Typescript compiler error, looks like we need to [change the compiler-target](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#jsx-factories) for `jsx` in our `tsconfig`. 

You can change this in our base.tsconfig [here](https://github.com/equinor/design-system/blob/b2045bb8e1b0149be02211f74dd63e284ab9d442/tsconfig.base.json#L16).

setting it from `react` to `react-jsx` seemed to do the trick

2021-04-20 19:45 UTC, Serjeel-Ranjan-911 commented
@mimarz help needed.

2021-04-21 06:01 UTC, mimarz commented
> @mimarz help needed.

Do you have linting enabled locally? :) You can see the error [here](https://github.com/equinor/design-system/pull/1251/checks?check_run_id=2394147777#step:3:395) nonetheless. Just a missing newline :)

2021-04-21 06:16 UTC, Serjeel-Ranjan-911 commented
> > @mimarz help needed.
> 
> Do you have linting enabled locally? :) You can see the error [here](https://github.com/equinor/design-system/pull/1251/checks?check_run_id=2394147777#step:3:395) nonetheless. Just a missing newline :)

sorry I don't have linter enabled. The error is so big I don't know which line needs a newline. I have not worked with linter before.

2021-04-21 12:04 UTC, mimarz commented
> > > @mimarz help needed.
> > 
> > 
> > Do you have linting enabled locally? :) You can see the error [here](https://github.com/equinor/design-system/pull/1251/checks?check_run_id=2394147777#step:3:395) nonetheless. Just a missing newline :)
> 
> sorry I don't have linter enabled. The error is so big I don't know which line needs a newline. I have not worked with linter before.

There is only one error, and the link above highlights it, its this one if it wasn't clear: 
```
/home/runner/work/design-system/design-system/libraries/core-react/src/components/Table/Inner.context.tsx
  1:1  error  Expected 1 empty line after import statement not followed by another import  import/newline-after-import
```

2021-04-21 12:29 UTC, Serjeel-Ranjan-911 commented
@mimarz  finally all tests passed. I should have enabled linter in my pc.

2021-04-21 13:06 UTC, mimarz requested changes
Good piece of work here! 👍
Just noticed some small irregularities that probably snuck in while refactoring so many lines! 😅

2021-04-21 13:06 UTC, mimarz commented on libraries/core-react/src/components/Accordion/AccordionItem.tsx
> +import { Children as ReactChildren, cloneElement } from 'react'
Looks like you ended up with double import statements from `react` (line 1 and line 9) here, so suggest changing it to just one :)

2021-04-21 17:21 UTC, mimarz approved these changes
Thank you very much for contributing @Serjeel-Ranjan-911  👍 

Appreciate the help!

2021-04-21 17:28 UTC, Serjeel-Ranjan-911 commented
> Thank you very much for contributing @Serjeel-Ranjan-911  👍 
> 
> Appreciate the help!

@mimarz your welcome. I never contributed to such a big repo before. I am trying to learn open source contribution. Also if anyone interested can exchange follow with me :)

Typescript was really useful for immediately finding where the code is breaking, although I never coded on it maybe I will consider using it.

2021-04-22 07:34 UTC, pomfrida approved these changes
LGTM 👍

2021-04-22 07:36 UTC, merged

2021-04-22 10:52 UTC, mimarz commented
> > Thank you very much for contributing @Serjeel-Ranjan-911  👍
> > Appreciate the help!
> 
> @mimarz your welcome. I never contributed to such a big repo before. I am trying to learn open source contribution. Also if anyone interested can exchange follow with me :)
> 
> Typescript was really useful for immediately finding where the code is breaking, although I never coded on it maybe I will consider using it.

Always good to contribute to open-source projects :) Might I ask where you heard about this project? Always interesting to hear :) @Serjeel-Ranjan-911

2021-04-22 10:55 UTC, Serjeel-Ranjan-911 commented
@mimarz  truly speaking I just roam around in issues section and work on issues which I can.