[WIP] 📝  Add compact mode stories
equinor/design-system pull request #1710
Opened 2021-11-18 14:54 UTC by vnys

resolves #1707

2021-11-24 13:23 UTC, mimarz commented
Looks like [@storybook/client-api ](https://github.com/storybookjs/storybook/tree/next/lib/client-api) is deprecated, or I am i reading it wrong?

2021-11-24 13:42 UTC, vnys commented
> Looks like [@storybook/client-api ](https://github.com/storybookjs/storybook/tree/next/lib/client-api) is deprecated, or I am i reading it wrong?

It looks like it _will_ be deprecated, as that is on the `next` branch.

2021-11-24 13:49 UTC, mimarz commented
> > Looks like [@storybook/client-api ](https://github.com/storybookjs/storybook/tree/next/lib/client-api) is deprecated, or I am i reading it wrong?
> 
> It looks like it _will_ be deprecated, as that is on the `next` branch.

Looking at the documentation for `@storybook/client-api` it looks like `@storybook/api` provides the same functionality.

2021-11-24 14:18 UTC, mimarz requested changes
We should probably have a talk on how we do the wording on the "developer documentation".   Added some suggestions. We need a "Developer Writer" 😂

Also I could not get the props table to work, making the use of the storybook-api redunant as I it was not interactable for me. 🤔

2021-11-24 14:18 UTC, mimarz commented on libraries/core-react/src/components/EdsProvider/EdsProvider.stories.mdx
> +Use the `<EdsProvider />` to provide users with the option of compressing the user interface to see more information at the same time without having to scroll.
We have not talked to much on how we formulate our stories in Storybook, but I think this is to much text to have as an intro to the component, i felt like being hit by a wall of text and had to strive to read through it.

This feels like more of an explanation of _why_ we have a density property in EDS and not just the components, but ofcourse, there are other reasons for why this is written here not instead 🙈

Maybe the intro could be short and consice that the `EdsProvdier` is a provider for setting "settings" for the eds react components, and then have a new heading with "Accessibility" (which we should have on all our stories in the future imho) where we explain the importancy of switcher for `density`

2021-11-24 14:18 UTC, mimarz commented on libraries/core-react/src/components/EdsProvider/EdsProvider.stories.mdx
> +  args={{  density: 'comfortable' }} />
I don't think you need to set the explicitly? Should be derived from default value of props.

2021-11-24 14:18 UTC, mimarz commented on libraries/core-react/src/components/EdsProvider/EdsProvider.stories.tsx
> +export const Default: Story<EdsProviderProps['density']> = (args) => {
Why should we hide the `children` property? Its just as important to communicate is required in the props table.

2021-11-24 14:18 UTC, mimarz commented on libraries/core-react/src/components/EdsProvider/EdsProvider.stories.tsx
> +  const [_, setState] = useArgs()
I assume this was to update the "props table"? Didn't seem to work on my machine as I had no controls for this prop in the props table as we usually have...

2021-11-24 14:18 UTC, mimarz commented on libraries/core-react/src/components/EdsProvider/EdsProvider.stories.tsx
> +const sourceCode = `const [state, setState] = useState<{
My initial impression is that this is a bad bad idea in terms of maintenance and keep the preview updated, why do this? I get that this was to have a clean sourc-code example but it feels excessive and prone to errors when trying to maintane updated code examples.

Maybe just have the `density` state in the actual code and comment where you set the `setArgs` with that its a storybook thing?

2021-11-24 14:53 UTC, vnys commented
There’s a reason I said in the standup this morning we should do a code review on Teams 😁 There’s much to discuss here. I’ll call for a meeting.

2021-11-25 09:34 UTC, vnys commented
> Looking at the documentation for `@storybook/client-api` it looks like `@storybook/api` provides the same functionality.

Good, I’ll update that then.

2021-12-20 01:00 UTC, vnys commented
Closing this issue now that Zeroheight is up and running. Made a separate issue for documenting the EdsProvider. (#1814)

2021-12-20 01:00 UTC, closed without merging