🚧 [WIP] add ThemeProvider to Dialog components
equinor/design-system pull request #1767
Opened 2021-12-03 06:26 UTC by laliq

resolves #1755

2021-12-06 11:35 UTC, mimarz requested changes
Looking good.
Looks like thing went abit fast and you missed updating some `styled` declarations in the sub-components to use theme prop instead of global token. 🤪 
As far as I could see,  line 6 in `Actions.tsx`, line 7 & 23 in `CustomContent.tsx` and line 7 in `Title.tsx`

2021-12-06 11:35 UTC, mimarz commented on libraries/core-react/src/components/Dialog/Dialog.tokens.ts
> +      height: shape._modes.compact.straight.minHeight,
Suggest removing this for now as `height` is not used in the component and we also don't know how the "compact" dialog should look like.

2021-12-10 12:53 UTC, oddvernes approved these changes
LGTM 👍

2021-12-13 07:25 UTC, mimarz commented on libraries/core-react/src/components/Dialog/Dialog.stories.tsx
> +  const [density] = useState<Density>('comfortable')
this should probably be `compact` for testing compact?

2021-12-13 13:04 UTC, mimarz approved these changes
LGTM 👍

2021-12-13 13:47 UTC, merged