✨ Added support for compact Snackbar
equinor/design-system pull request #1773
Opened 2021-12-06 12:01 UTC by laliq

resolves #1756

2021-12-06 12:31 UTC, mimarz requested changes
The default value for `minHeight` should probably be changed to the [correct shape in Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17659%3A40216)

Looks like you missed to updated `SnackbarActions` styled component with new theme syntax.

2021-12-06 12:31 UTC, mimarz commented on libraries/core-react/src/components/Snackbar/Snackbar.tokens.ts
> +      height: shape._modes.compact.straight.minHeight,
Looks like this should be `minHeight` as its what used in the "default".

2021-12-10 14:06 UTC, oddvernes approved these changes
LGTM 👍

2021-12-13 07:30 UTC, mimarz commented on libraries/core-react/src/components/Snackbar/Snackbar.stories.tsx
> +  const [density] = useState<Density>('comfortable')
Should probably be `compact` here aswell?

2021-12-13 12:57 UTC, mimarz approved these changes
LGTM 👍

2021-12-13 13:47 UTC, merged