[WIP] Create eds-utils
equinor/design-system pull request #1852
Opened 2022-01-03 12:28 UTC by oddvernes

resolves #1846

2022-01-05 08:25 UTC, mimarz requested changes
Looking good, some small nitpicking.

* You can removed `nginx.conf` as there is nothing here we will host on a webserver standalone.
* Suggest add a `build:utils` and `test:utils` scripts to the root `package.yaml` so we have the same shortcuts as for our other packages.

2022-01-05 08:47 UTC, oddvernes commented
test fails btw because there are no tests. So we should either not add test as ci step, or add a test/mock test

2022-01-05 08:51 UTC, mimarz commented
> test fails btw because there are no tests. So we should either not add test as ci step, or add a test/mock test

Just make a simple test for for `useMounted` perhaps?

2022-01-05 10:55 UTC, vnys requested changes
Just some missing info. Also, we should add some documentation to the Storybook. Have a look at Circuit UI’s storybook for an example.

2022-01-05 10:55 UTC, vnys commented on packages/eds-utils/README.md
> +This package host hooks and utility functions that are used by eds-core-react and eds-lab.
```suggestion
This package host hooks and utility functions that are used by [eds-core-react](https://www.npmjs.com/package/@equinor/eds-core-react) and [eds-lab](https://www.npmjs.com/package/@equinor/eds-lab).
```

2022-01-05 10:55 UTC, vnys commented on packages/eds-utils/README.md
> +This package host hooks and utility functions that are used by eds-core-react and eds-lab.
Add links to eds-core-react and eds-lab

2022-01-06 15:21 UTC, vnys commented
About the tests… I think we need to agree on _why_ we write tests. I don’t see the value of writing a test just to make some system shut up. If we have 10 modules, and just one test, what’s the point? If we only focus on moving issues to the right on the board, does that mean that the job is done if we cut corners to get there? Or does it mean we have accumulated even more technical debt? If the point is to publish the package as quickly as possible because it’s a blocker, then we should at least create an issue for writing tests and move it to the top of the todo lane. We need to uphold a certain level of quality in EDS, having a good test coverage and writing good documentation is part of that.

2022-01-07 07:48 UTC, mimarz commented
> About the tests… I think we need to agree on _why_ we write tests. I don’t see the value of writing a test just to make some system shut up. If we have 10 modules, and just one test, what’s the point? If we only focus on moving issues to the right on the board, does that mean that the job is done if we cut corners to get there? Or does it mean we have accumulated even more technical debt? If the point is to publish the package as quickly as possible because it’s a blocker, then we should at least create an issue for writing tests and move it to the top of the todo lane. We need to uphold a certain level of quality in EDS, having a good test coverage and writing good documentation is part of that.

I think the idea was more to add remaining tests in a separate issue. Added an issue for this: #1868.

2022-01-07 08:00 UTC, mimarz approved these changes
LGTM 👍

2022-01-07 10:03 UTC, vnys approved these changes
Linting is missing, apart from that it LGTM 👍🏻

2022-01-07 11:29 UTC, merged