✅  Add a11y test for Input
equinor/design-system pull request #1961
Opened 2022-02-08 14:13 UTC by laliq

Resolves #1959

2022-02-09 08:37 UTC, laliq commented
Here is how [axe](https://dequeuniversity.com/rules/axe/4.2/label?application=axeAPI) describes the issue and solution.

2022-02-09 09:09 UTC, mimarz commented
> Here is how [axe](https://dequeuniversity.com/rules/axe/4.2/label?application=axeAPI) describes the issue and solution.

Jepp, its a good explanation for the a11y rules for `input` fields :) 

Since we are basically just wrapping an `input` field with our `Input` component I suggest making two a11y test that cover the use-cases in which we used this component. One for `aria-label` and the other using a `label`, either wrapped or by using the `for` property with `id`.

2022-02-10 11:32 UTC, mimarz requested changes
Suggest just typing the label text in the label, noe need for variable interpolation if its not needed.

2022-02-10 11:32 UTC, mimarz commented on packages/eds-core-react/src/components/Input/Input.test.tsx
> +    const label = 'Input'
```suggestion
```

2022-02-10 11:32 UTC, mimarz commented on packages/eds-core-react/src/components/Input/Input.test.tsx
> +        {label}
```suggestion
        Label text
```

2022-02-10 15:34 UTC, merged