🔧  Add extension Stylelint
equinor/design-system pull request #2072
Opened 2022-03-09 14:55 UTC by laliq

Resolves #2071

2022-03-17 07:46 UTC, mimarz requested changes
Suggest also adding this extension to `.vscode/extensions.json` so that people not using codespaces also have it :)

2022-03-21 07:28 UTC, vnys requested changes

2022-03-21 07:28 UTC, vnys commented on .stylelint.json
> +    "stylelint-config-recommended",
```suggestion
```

The standard config [already extends recommended](https://github.com/stylelint/stylelint-config-standard/blob/main/index.js#L4) so we can remove this line.

2022-03-22 07:24 UTC, mimarz requested changes
Stylelint out of the box only works for css or scss files I belive. Since most of our styling uses styled-components, we need to use a processor for the stylelint to work on _that_ styling.

https://styled-components.com/docs/tooling#stylelint

2022-09-28 07:47 UTC, mimarz commented
Closing this as its quite outdated by now 👴

2022-09-28 07:47 UTC, closed without merging