📝♿️ Progress a11y
equinor/design-system pull request #2182
Opened 2022-05-03 15:08 UTC by oddvernes

resolves #2020

2022-05-10 13:59 UTC, oddvernes commented
> When testing the accessibility story for linear and circular the voice over is stuck on "loading 0%" 🤔

Well first of all I am going to rebase on develop, stand by

2022-05-10 14:13 UTC, oddvernes commented
Hmm it looks like the mac voiceover reads out a bunch of stuff that is not read on windows. It is not supposed to read loading percentages for indeterminate loader. I need to investigate more on mac. The determinate loader demos on circular and linear works as it is supposed

2022-05-18 13:23 UTC, oddvernes commented
Fixed mac issue by not including output element for indeterminate

2022-05-23 11:43 UTC, mimarz commented
VoiceOver on Mac does not seem to read out loading states for linear and star accessibility stories... 🤔

2022-05-23 11:43 UTC, mimarz requested changes
VoiceOver on Mac does not seem to read out loading states for linear and star accessibility stories... 🤔

2022-05-23 13:17 UTC, oddvernes commented
It was due to aria-busy. I removed it and made aria-live assertive as well so the loading readout interrupts the long winded readout of the button context

2022-05-31 08:30 UTC, mimarz approved these changes
Works now! ♿

2022-06-01 10:26 UTC, merged