📝  Native Select documentation
equinor/design-system pull request #2243
Opened 2022-05-24 12:24 UTC by martalalik

Resolves #420

2022-05-30 07:27 UTC, oddvernes commented on packages/eds-core-react/src/components/Select/NativeSelect/NativeSelect.docs.mdx
> +We recommend using `NativeSelect` on products with limited space as it provides a better user experience.
"on products with limited space" I'm a little confused what this sentence means. Do you mean in UI's with limited space?

2022-05-30 07:27 UTC, oddvernes commented on packages/eds-core-react/src/components/Select/NativeSelect/NativeSelect.docs.mdx
> +We recommend using `NativeSelect` on products with limited space as it provides a better user experience.
"on products with limited space" I'm a little confused what this sentence means. Do you mean in UI's with limited space?

2022-05-31 09:54 UTC, mimarz requested changes

2022-05-31 09:54 UTC, mimarz commented on packages/eds-core-react/src/components/Select/NativeSelect/NativeSelect.docs.mdx
> +We recommend using `NativeSelect` on products with limited space as it provides a better user experience.
Should also add for simples use and best accessibility support we recommend native select :)

2022-05-31 13:54 UTC, merged