📝 Icon documentation
equinor/design-system pull request #2249
Opened 2022-05-30 06:33 UTC by martalalik

Resolves #446

2022-05-30 06:51 UTC, martalalik commented
I'm not sure to the `Size` description. 
In the example we have icon sizes from `16px` to `48px`, while in [documentation](https://eds.equinor.com/0b0c666ab/p/347dd6-system-icons/b/25520a) there are mention sizers form `16px` to `24px`. 🤔

2022-05-31 09:57 UTC, mimarz requested changes

2022-05-31 09:57 UTC, mimarz commented on packages/eds-core-react/src/components/Icon/Icon.docs.mdx
> +    <li>System icons can be used in 24px and 16px sizes.</li>
Suggest removing these two paragraphs as the sizes in props table speaks for them selves. Good to mention when its recommended to use 18 px as its the odd one out

2022-05-31 09:59 UTC, mimarz commented on packages/eds-core-react/src/components/Icon/Icon.stories.tsx
> +    {' '}
Remove space blunder

2022-05-31 09:59 UTC, mimarz commented on packages/eds-core-react/src/components/Icon/Icon.stories.tsx
> +    {' '}
```suggestion
```

2022-06-01 13:23 UTC, merged