📝 Split Button story into sub-directories
equinor/design-system pull request #2528
Opened 2022-09-28 11:08 UTC by martalalik

Resolves #2509

2022-09-28 13:13 UTC, mimarz requested changes
1. Suggest just sticking to one variant for the "Button.Group" examples. Having one unlike the other makes it look like the toggle button when its not... Suggest just sticking to default `<Button>`

2. Maybe just call the parent directory just "Button" instead of "Buttons"? "Button" felt more natural and in line with the sub-components and such

2022-09-28 13:13 UTC, mimarz commented on packages/eds-core-react/src/components/Button/ButtonGroup/ButtonGroup.docs.mdx
> +The `Button.Group` can be displayed vertically using the `vertical` prop.
Suggest merging these into one story and just calling it "orientation"? Then just have both the horizontal and vertical in the same story.

2022-09-28 13:27 UTC, martalalik commented
> 2. Maybe just call the parent directory just "Button" instead of "Buttons"? "Button" felt more natural and in line with the sub-components and such

Definitely 😅

2022-09-28 13:59 UTC, oddvernes commented
I noticed this warning when making a build (from develop not this branch):
```
(!) Circular dependency
src/components/Button/index.ts -> src/components/Button/ToggleButton/ToggleButton.tsx -> src/components/Button/index.ts
```

2022-09-29 10:23 UTC, mimarz requested changes

2022-09-29 10:23 UTC, mimarz commented on packages/eds-core-react/src/components/Button/ButtonGroup/ButtonGroup.stories.tsx
> +      <Button variant="outlined">Outlined</Button>
```suggestion
      <Button>Button</Button>
      <Button>Button</Button>
      <Button>Button</Button>
      <Button>Button</Button>
```

2022-09-29 10:23 UTC, mimarz commented on packages/eds-core-react/src/components/Button/ButtonGroup/ButtonGroup.stories.tsx
> +    <Button variant="outlined">Outlined</Button>
```suggestion
    <Button>Button</Button>
    <Button>Button</Button>
    <Button>Button</Button>
    <Button>Button</Button>
```

2022-09-29 10:23 UTC, mimarz commented on packages/eds-core-react/src/components/Button/ButtonGroup/ButtonGroup.stories.tsx
> +    <Button variant="outlined">Outlined</Button>
```suggestion
    <Button>Button</Button>
    <Button>Button</Button>
    <Button>Button</Button>
    <Button>Button</Button>
```

2022-09-29 10:23 UTC, mimarz commented on packages/eds-core-react/src/components/Button/ButtonGroup/ButtonGroup.stories.tsx
> +        <Button variant="outlined">Outlined</Button>
```suggestion
    <Button>Button</Button>
    <Button>Button</Button>
    <Button>Button</Button>
    <Button>Button</Button>
```

2022-09-29 11:11 UTC, oddvernes approved these changes
LGTM, just fix linting errors in ButtonGroup.stories

2022-09-29 11:32 UTC, mimarz approved these changes
LGTM 👍

2022-09-29 11:41 UTC, merged