:sparkles: Improve data grid
equinor/design-system pull request #3231
Opened 2024-01-23 07:37 UTC by magnh

resolves #3234 

## What does this pull request change?

This pull request introduces the following improvements to the data-grid:

Most of these changes have been discussed with @yusijs.

- ✨ Reexport `@tanstack/react-table` types to ease typing in apps using the data grid
- 📌 Move eds-core-react to peer dependencies
  - This is neccessary because EDS uses React Context and the grid and the project should
have the same React instance running. This makes it possible to set EDS Density of the
table above the component.
- ♻️ Move text truncating into default cell to enable overwriting cell content
  - This enables custom cells like popover, autocomplete or other cells that overflows the cell itself.
- 🐛 Inherit row background color for pinned cells
  - This ensures hover color on the whole row when columns are pinned
- 🐛 Support 100% width
  - Support string `width` and `height`
- ✨ Allow setting minWidth of table
- ✨ Expose getRowId callback from react-table
- ✨ Expose virtualizer ref
  - This is needed to be able to run "scroll to" functionality in apps.
- 🐛 Hide virtualizer rows top and bottom rows when not needed

## Why is this pull request needed?

In order to implement this in our project, we need to be able to use custom cells, set 100% width and use the EdsProvider with the table. Also, there are some minor bugs discovered during implementation.

2024-01-23 08:21 UTC, oddvernes commented
> I cannot edit reviewers, but I would like a review from @yusijs 😄
> 
> It seems like the checks are failing due to a missing secret, but I'm not sure whether it's on my side or yours?

 I have added @yusijs as a reviewer 🙂 
The checks failing from forked pull requests are on our end. We need to fix the github action, but in the meantime we  can run the tests locally 👍

2024-01-23 08:46 UTC, yusijs requested changes

2024-01-23 08:46 UTC, yusijs commented on packages/eds-data-grid-react/src/EdsDataGrid.tsx
> +          contain: 'strict',
Change this to `contain: layout paint style` to ensure auto height works

2024-01-23 09:10 UTC, oddvernes commented
✅ Lint
✅ Tests
✅ Types

2024-01-23 15:01 UTC, oddvernes commented
lint/test/types all seems to be in order still 👍

2024-01-24 08:10 UTC, yusijs approved these changes
LGTM!

2024-01-24 08:43 UTC, oddvernes approved these changes
LGTM!

2024-01-24 09:07 UTC, oddvernes commented
Yes I will merge 👍 Was just trying the build downstream in an app for the final test  but looks good

2024-01-24 09:09 UTC, merged