Release core-react v0.6.0 & tokens v0.4.0
equinor/design-system pull request #536
Opened 2020-09-02 09:01 UTC by mimarz

Preparing new release

- [ ] core-react v0.6.0
- [ ] tokens v0.4.0
- [ ] publish new storybook

2020-09-02 13:14 UTC, pomfrida approved these changes
🎉

2020-09-03 06:46 UTC, vnys requested changes
Remember to bump the version of the storybook to the same version as the react components. And use lists in the changelog even though there’s only one item.

2020-09-03 06:46 UTC, vnys commented on libraries/tokens/CHANGELOG.md
> +Added missing overlay color `pressed_overlay_light`
```suggestion
- Added missing overlay color `pressed_overlay_light`
```

2020-09-03 06:46 UTC, vnys commented on libraries/tokens/CHANGELOG.md
> +Removed unused colors in EDS
```suggestion
- Removed unused colors in EDS
```

2020-09-03 06:46 UTC, vnys commented on libraries/tokens/CHANGELOG.md
> +- `field__fill_resting`
```suggestion
  - `field__fill_resting`
```

2020-09-03 06:46 UTC, vnys commented on libraries/tokens/CHANGELOG.md
> +- `field__fill_hover`
```suggestion
  - `field__fill_hover`
```

2020-09-03 06:46 UTC, vnys commented on libraries/tokens/CHANGELOG.md
> +- `field__fill_activated`
```suggestion
  - `field__fill_activated`
```

2020-09-03 06:46 UTC, vnys commented on libraries/tokens/CHANGELOG.md
> +Changed `link_in_snackbars` for better contrast.
```suggestion
- Changed `link_in_snackbars` for better contrast.
```

2020-09-03 07:14 UTC, vnys approved these changes
LGTM 👍

2020-09-03 10:54 UTC, merged