[WIP]: Toc types
equinor/design-system pull request #689
Opened 2020-10-16 10:36 UTC by wenche

Resolve #558

2020-10-16 10:37 UTC, wenche commented
Started to write Type for the token object, but since it on a completely different format than the other tokens, it didn't make sense beyond TS automatic detection 🤷‍♀️  Should probably be aligned with a more common token object format

2020-10-16 10:43 UTC, vnys commented
I’m scratching my head a bit too with the Dialog tokens… not sure if it gives us something or if it’s just a waste of time

2020-10-16 10:48 UTC, wenche commented
It gives us something if we use a common format, but quite a few of the components does not

2020-10-19 07:59 UTC, vnys commented
/azp run react-tests

2020-10-19 12:53 UTC, wenche commented
/azp run react-tests

2020-10-20 07:33 UTC, mimarz commented on libraries/core-react/src/TableOfContents/TableOfContents.tsx
>  import { List, Typography } from '..'
This needs to be updated to direct imports instead of .. imports #708

2020-10-20 07:37 UTC, mimarz commented on libraries/core-react/src/TableOfContents/TableOfContents.tsx
> +const TocList = styled((props: ListType) => <List {...props} />)`
This has nothing to do with the typescript rewrite, more clean code. But these should be normal "extends". 

For examples; 
`const TocList = styled((props: ListType) => <List {...props} />)` 
is equivalent 
 `const TocList = styled(List)`

2020-10-20 07:41 UTC, mimarz requested changes
Looks good from a typescript point of view. Need to fix some imports as discovered in #708 for tests to run. We have also updated the failing test, so rebasing with latest from typescript to test could help.

There is also a clean code mention I think you can do. This would eliminate the need to export `ListType` from `<List>`

2020-10-20 11:51 UTC, wenche commented
Moved to #714 to avoid lot's of changes outside the TOC changes 🙈

2020-10-20 11:51 UTC, closed without merging