[WIP]: Working with typescript
equinor/design-system pull request #730
Opened 2020-10-23 06:43 UTC by wenche

Resolve #728

2020-10-23 06:55 UTC, wenche commented
I'm having a hard time with this one.

`useKeyPress.ts `Doesn't seem like this is actually in use, should probably be deleted?

`useCombinedRefs.ts` I was trying [this approach](https://github.com/facebook/react/issues/13029#issuecomment-497641073) but it gives a lot of errors in the component using this function along with eslint complaining on `any`

`setReactInputValue`  🙈  This use private React stuffs.... 

`useOutsideClick` I think this one is OK 😓

2020-10-23 07:12 UTC, mimarz commented
Would this work for `useCombinedRefs` ? 

```typescript
import { useRef, useEffect } from 'react'
type Ref = React.MutableRefObject<HTMLElement>
type useCombinedRefsProps<T> = T | ((a: HTMLElement) => T)
export const useCombinedRefs = (...refs: useCombinedRefsProps<Ref>[]): Ref => {
  const targetRef = useRef<HTMLElement>(null)
  useEffect(() => {
    refs.forEach((ref) => {
      if (!ref) return
      if (typeof ref === 'function') {
        ref(targetRef.current)
      } else {
        ref.current = targetRef.current
      }
    })
  }, [refs])
  return targetRef
}
```

2020-10-23 07:35 UTC, wenche commented
Let's try!

2020-10-23 07:44 UTC, wenche commented
Tried and there's no issues with the `useCombinedRefs` file itself. But the same problems in `TabList` and `Menu` remain. 
```
[!] (plugin rpt2) Error: /Users/wenche/Documents/prosjekter/equinor/migrate-common/libraries/core-react/src/Tabs/TabList.tsx(73,27): semantic error TS2345: Argument of type 'LegacyRef<HTMLButtonElement>' is not assignable to parameter of type 'Ref<HTMLElement>'.
  Type 'string' is not assignable to type 'Ref<HTMLElement>'.
``` 

I don't know what the LegacyRef is 🤔  Have to google that
```
[!] (plugin rpt2) Error: /Users/wenche/Documents/prosjekter/equinor/migrate-common/libraries/core-react/src/Menu/MenuItem.tsx(124,9): semantic error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Pick<Pick<Pick<DetailedHTMLProps<LiHTMLAttributes<HTMLLIElement>, HTMLLIElement>, "slot" | "style" | ... 253 more ... | "value"> & { ...; } & StyleProps, "active" | ... 257 more ... | "value"> & Partial<...>, "active" | ... 257 more ... | "value"> & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type 'Ref' is not assignable to type 'Ref<HTMLLIElement>'.
      Type 'MutableRefObject<HTMLElement>' is not assignable to type 'RefObject<HTMLLIElement>'.
        Types of property 'current' are incompatible.
          Type 'HTMLElement' is missing the following properties from type 'HTMLLIElement': type, value
  Overload 2 of 2, '(props: StyledComponentPropsWithAs<"li", any, StyleProps, never>): ReactElement<StyledComponentPropsWithAs<"li", any, StyleProps, never>, string | ... 1 more ... | (new (props: any) => Component<...>)>', gave the following error.
    Type 'Ref' is not assignable to type 'Ref<HTMLLIElement>'.
      Type 'MutableRefObject<HTMLElement>' is not assignable to type 'RefObject<HTMLLIElement>'.
```

2020-11-05 11:04 UTC, mimarz commented
It is what it is, a hack. React does not provide internal types (that I could find) so we have to make it work with just faking it.

Suggestion:
```typescript
// Workaround
// React ignores 'dispathEvent' on input/textarea, see https://github.com/facebook/react/issues/10135
type ReactInternalHack = { _valueTracker?: { setValue: (a: string) => void } }

export const setReactInputValue = (
  input: HTMLInputElement & ReactInternalHack,
  value: string,
): void => {
  const previousValue = input.value

  input.value = value

  const tracker = input._valueTracker

  if (typeof tracker !== 'undefined') {
    tracker.setValue(previousValue)
  }

  //'change' instead of 'input', see https://github.com/facebook/react/issues/11488#issuecomment-381590324
  input.dispatchEvent(new Event('change', { bubbles: true }))
}

```

You will also need to cast the `input` on line 217, in `<Search />` to `HTMLInputElement` for now...

2020-11-05 11:46 UTC, mimarz commented
I had a second look at `useCombinedRefs` as we got a the wrong type in return when using it in for example `Search`.

New suggested `useCombinedRefs`
```typescript
import { useRef, useEffect, MutableRefObject } from 'react'

type Ref<T> = MutableRefObject<T>
type Props<T, P> = T | ((a: P) => void)

export const useCombinedRefs = <T extends HTMLElement>(
  ...refs: Props<Ref<T>, T>[]
): Ref<T> => {
  const targetRef = useRef<T>(null)
  useEffect(() => {
    refs.forEach((ref) => {
      if (!ref) return
      if (typeof ref === 'function') {
        ref(targetRef.current)
      } else {
        ref.current = targetRef.current
      }
    })
  }, [refs])
  return targetRef
}
```

2020-11-09 08:57 UTC, wenche commented
I'm not sure about this one
```
type TabChild = ButtonHTMLAttributes<HTMLButtonElement> &
  RefAttributes<HTMLButtonElement> &
  ReactElement
```
but it did remove the ts errors 🤷‍♀️

2020-11-09 09:04 UTC, mimarz commented
> I'm not sure about this one
> 
> ```
> type TabChild = ButtonHTMLAttributes<HTMLButtonElement> &
>   RefAttributes<HTMLButtonElement> &
>   ReactElement
> ```
> 
> but it did remove the ts errors 🤷‍♀️

The tabs are `ButtonElement` so why not 🙈  Lets test 🙂

2020-11-09 10:15 UTC, wenche commented
@mimarz  What do you suggest for this error?
![Skjermbilde 2020-11-09 kl  11 14 40](https://user-images.githubusercontent.com/1568252/98528625-db920100-227c-11eb-82be-d92b05f4bd34.png)

2020-11-09 13:05 UTC, mimarz commented on libraries/core-react/src/Menu/MenuItem.tsx
> +          (el: HTMLElement) => isFocused && el.focus(),
This looks to be the wrong type (from ts convert). `el` argument should be `HTMLLIElement`? Might aswell fix it now since you are here 😅

2020-11-09 13:11 UTC, mimarz requested changes
Just one small type fix from before we could fix while touching this file, else it looks good 👍

2020-11-09 13:18 UTC, mimarz approved these changes
LGTM 👍

2020-11-09 13:21 UTC, merged