[WIP]: Migrate Card story to typescript
equinor/design-system pull request #756
Opened 2020-10-27 12:12 UTC by wenche

Part of #735

2020-10-27 13:37 UTC, wenche commented
I'm having an issue with the first tab being renamed to Story. Will hopefully be [fixed soon](url)https://github.com/storybookjs/storybook/issues/12357

2020-10-27 13:39 UTC, wenche commented
I had to use the `JSX.IntrinsicElements` trick for the args table to show. I wasn't enough with `React.HTMLAttributes` 🤷‍♀️

2020-10-28 07:13 UTC, mimarz commented on libraries/core-react/src/Card/CardActions.tsx
>    function EdsCardActions(
Missed function renameing

2020-10-28 07:16 UTC, mimarz commented on apps/storybook-react/stories/Card.stories.tsx
> +// import { withKnobs, select, boolean } from '@storybook/addon-knobs'
Suggest we just remove this if we aren't using. Going to be replace by `controls` anyways #757

2020-10-28 07:18 UTC, mimarz requested changes
Some small stuff

2020-10-28 07:28 UTC, mimarz approved these changes
LGTM 👍

2020-10-28 07:32 UTC, merged